name: Story
description: Story Issue
title: "[Story]: "
labels: ["story"]
projects: ["sgmdq729/1"]
body:
  - type: textarea
    id: story-details
    attributes:
      label: task details
      value: "🧑誰が：\n🗯要求：\n❓理由："
